# Generated by Django 3.0.7 on 2020-06-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200620_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Digital')),
                ('fiber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Fiber')),
                ('figurative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Figurative')),
            ],
        ),
    ]
