# Generated by Django 3.0.7 on 2020-06-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='figurative',
        ),
    ]
