# Generated by Django 3.0.7 on 2020-06-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200620_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='FiberPhoto',
        ),
    ]
